/**
 * Generated by tsnapi — public API snapshot of `local-postgres/core`
 */
// #region Interfaces
export interface EnsurePostgresDatabaseOptions {
  listen: PostgresListenOptions;
  database: string;
  bootstrapDatabase?: string;
  user?: string;
  password?: string;
}
export interface InitPostgresDataDirOptions {
  dataDir: string;
  binaries?: ResolvedPostgresBinaries;
  postgres?: PostgresBinaryOptions;
  encoding?: string;
  locale?: string | false;
  username?: string;
  auth?: string;
  noSync?: boolean;
  config?: Record<string, PostgresConfigValue>;
  log?: LocalPostgresLogTarget;
  logger?: Partial<LocalPostgresLogger>;
}
export interface InitPostgresDataDirResult {
  dataDir: string;
  version?: string;
}
export interface LocalPostgresLogger {
  info(_: string): void;
  warn(_: string): void;
  error(_: string): void;
}
export interface LocalPostgresProcess {
  dataDir: string;
  listen: ResolvedPostgresListenOptions;
  port: number;
  host?: string;
  socketDir?: string;
  pid?: number;
  stop(): Promise<void>;
  [Symbol.asyncDispose](): Promise<void>;
}
export interface PostgresBinaryOptions {
  version?: string;
  strategy?: PostgresBinaryStrategy;
  cacheDir?: string;
}
export interface ResolvedPostgresBinaries {
  initdb: string;
  postgres: string;
  pgCtl?: string;
  createdb?: string;
  psql?: string;
  source: 'local' | 'download';
  version?: string;
}
export interface StartPostgresDataDirOptions {
  dataDir: string;
  binaries?: ResolvedPostgresBinaries;
  listen?: PostgresListenOptions;
  postgres?: PostgresBinaryOptions;
  postgresOptions?: string[];
  log?: LocalPostgresLogTarget;
  logger?: Partial<LocalPostgresLogger>;
  readinessTimeoutMs?: number;
  readinessIntervalMs?: number;
  stopTimeoutMs?: number;
}
export interface StopPostgresDataDirOptions {
  dataDir: string;
  binaries?: ResolvedPostgresBinaries;
  listen?: PostgresListenOptions;
  postgres?: PostgresBinaryOptions;
  mode?: 'smart' | 'fast' | 'immediate';
  waitForIdle?: boolean | {
    database?: string;
    minConnections?: number;
    timeoutMs?: number;
    intervalMs?: number;
  };
  timeoutMs?: number;
  log?: LocalPostgresLogTarget;
  logger?: Partial<LocalPostgresLogger>;
}
export interface WaitForPostgresReadyOptions {
  listen: PostgresListenOptions;
  database?: string;
  user?: string;
  password?: string;
  timeoutMs?: number;
  intervalMs?: number;
}
// #endregion

// #region Types
export type LocalPostgresLogTarget = 'ignore' | 'inherit' | {
  filePath: string;
};
export type PostgresBinaryStrategy = 'local-only' | 'prefer-local' | 'prefer-download' | 'download-only';
export type PostgresConfigValue = string | number | boolean;
export type PostgresListenOptions = {
  type: 'tcp';
  host?: string;
  port?: number;
} | {
  type: 'socket';
  socketDir: string;
  port?: number;
};
export type ResolvedPostgresListenOptions = {
  type: 'tcp';
  host: string;
  port: number;
} | {
  type: 'socket';
  socketDir: string;
  port: number;
};
// #endregion

// #region Classes
export declare class LocalPostgresError extends Error {
  constructor(_: string, _?: ErrorOptions);
}
// #endregion

// #region Functions
export declare function ensurePostgresDatabase(_: EnsurePostgresDatabaseOptions): Promise<void>;
export declare function getPostgresVersion(_?: {
  postgres?: PostgresBinaryOptions;
}): Promise<string>;
export declare function initPostgresDataDir(_: InitPostgresDataDirOptions): Promise<InitPostgresDataDirResult>;
export declare function resolvePostgresBinaries(_?: PostgresBinaryOptions): Promise<ResolvedPostgresBinaries>;
export declare function startPostgresDataDir(_: StartPostgresDataDirOptions): Promise<LocalPostgresProcess>;
export declare function stopPostgresDataDir(_: StopPostgresDataDirOptions): Promise<void>;
export declare function waitForPostgresReady(_: WaitForPostgresReadyOptions): Promise<void>;
// #endregion

// #region Variables
export declare const DEFAULT_POSTGRES_CACHE_DIR: string;
// #endregion