/**
 * Generated by tsnapi — public API snapshot of `local-postgres`
 */
// #region Interfaces
export interface LocalPostgresEnv {
  PGDATA: string;
  PGDATABASE: string;
  PGHOST: string;
  PGPORT: string;
  DATABASE_URL: string;
  PGUSER?: string;
  PGPASSWORD?: string;
}
export interface LocalPostgresLogger {
  info(_: string): void;
  warn(_: string): void;
  error(_: string): void;
}
export interface LocalPostgresServer {
  dataDir: string;
  database: string;
  listen: ResolvedPostgresListenOptions;
  host: string;
  port: number;
  socketDir?: string;
  user?: string;
  password?: string;
  pid?: number;
  connectionString: string;
  env: LocalPostgresEnv;
  stop(): Promise<void>;
  [Symbol.asyncDispose](): Promise<void>;
}
export interface LocalPostgresSuperuser {
  name: string;
  password: string;
}
export interface PostgresBinaryOptions {
  version?: string;
  strategy?: PostgresBinaryStrategy;
  cacheDir?: string;
}
export interface StartPostgresOptions {
  dataDir: string;
  database?: string;
  port?: number;
  host?: string;
  listen?: PostgresListenOptions;
  config?: Record<string, PostgresConfigValue>;
  superuser?: LocalPostgresSuperuser;
  log?: LocalPostgresLogTarget;
  postgres?: PostgresBinaryOptions;
  logger?: Partial<LocalPostgresLogger>;
  readinessTimeoutMs?: number;
  readinessIntervalMs?: number;
  stopTimeoutMs?: number;
}
// #endregion

// #region Types
export type LocalPostgresLogTarget = 'ignore' | 'inherit' | 'on-error' | {
  filePath: string;
};
export type PostgresBinaryStrategy = 'local-only' | 'prefer-local' | 'prefer-download' | 'download-only';
export type PostgresConfigValue = string | number | boolean;
export type PostgresListenOptions = {
  type: 'tcp';
  host?: string;
  port?: number;
} | {
  type: 'socket';
  socketDir: string;
  port?: number;
};
export type ResolvedPostgresListenOptions = {
  type: 'tcp';
  host: string;
  port: number;
} | {
  type: 'socket';
  socketDir: string;
  port: number;
};
// #endregion

// #region Classes
export declare class LocalPostgresError extends Error {
  readonly diagnostics?: string;
  constructor(_: string, _?: ErrorOptions & {
    diagnostics?: string;
  });
}
export declare class PostgresDataDirInUseError extends LocalPostgresError {
  readonly dataDir: string;
  readonly pid: number;
  constructor(_: string, _: number);
}
// #endregion

// #region Functions
export declare function startPostgres(_: StartPostgresOptions): Promise<LocalPostgresServer>;
// #endregion

// #region Variables
export declare const DEFAULT_POSTGRES_CACHE_DIR: string;
// #endregion