/**
 * Generated by tsnapi — public API snapshot of `local-postgres`
 */
// #region Interfaces
export interface LocalPostgresEnv {
  PGDATA: string;
  PGDATABASE: string;
  PGHOST: string;
  PGPORT: string;
  DATABASE_URL: string;
  PGUSER?: string;
  PGPASSWORD?: string;
}
export interface LocalPostgresLogger {
  info(_: string): void;
  warn(_: string): void;
  error(_: string): void;
}
export interface LocalPostgresServer {
  dataDir: string;
  database: string;
  host: string;
  port: number;
  user?: string;
  password?: string;
  pid?: number;
  connectionString: string;
  env: LocalPostgresEnv;
  stop(): Promise<void>;
}
export interface LocalPostgresSuperuser {
  name: string;
  password: string;
}
export interface PostgresBinaryOptions {
  version?: string;
  strategy?: PostgresBinaryStrategy;
  cacheDir?: string;
}
export interface StartPostgresOptions {
  dataDir: string;
  database?: string;
  port?: number;
  host?: string;
  superuser?: LocalPostgresSuperuser;
  log?: LocalPostgresLogTarget;
  postgres?: PostgresBinaryOptions;
  logger?: Partial<LocalPostgresLogger>;
  readinessTimeoutMs?: number;
  readinessIntervalMs?: number;
  stopTimeoutMs?: number;
}
// #endregion

// #region Types
export type LocalPostgresLogTarget = 'ignore' | 'inherit' | {
  filePath: string;
};
export type PostgresBinaryStrategy = 'local-only' | 'prefer-local' | 'prefer-download' | 'download-only';
// #endregion

// #region Classes
export declare class LocalPostgresError extends Error {
  constructor(_: string, _?: ErrorOptions);
}
// #endregion

// #region Functions
export declare function startPostgres(_: StartPostgresOptions): Promise<LocalPostgresServer>;
// #endregion

// #region Variables
export declare const DEFAULT_POSTGRES_CACHE_DIR: string;
// #endregion