/**
 * Generated by tsnapi — public API snapshot of `local-postgres/tmp`
 */
// #region Types
export type InitOptions = {
  postgres?: PostgresBinaryOptions;
  stdio?: StdioOptions;
};
export type PgTmp = {
  dsn: string;
  dataDir: string;
  stop(_?: StopOptions): Promise<void>;
  [Symbol.asyncDispose](): Promise<void>;
};
export type StartOptions = {
  dataDir?: string;
  host?: string | boolean;
  port?: number;
  timeout?: number;
  keep?: boolean;
  prewarm?: boolean;
  postgres?: PostgresBinaryOptions;
  postgresOptions?: string;
};
export type StopOptions = {
  keep?: boolean;
  timeout?: number;
  initialTimeout?: number;
  force?: boolean;
  host?: string;
  port?: number;
  stdio?: import('node:child_process').StdioOptions;
  verbose?: boolean;
};
// #endregion

// #region Functions
export declare function initdb(_?: string | null, _?: InitOptions): Promise<string>;
export declare function start(_?: StartOptions): Promise<PgTmp>;
export declare function stop(_: string, _?: StopOptions): Promise<void>;
// #endregion

// #region Variables
export declare const PREFIX: string;
// #endregion