export const DEFAULT_HOST = '127.0.0.1'
export const DEFAULT_DATABASE = 'postgres'
export const DEFAULT_READINESS_TIMEOUT_MS = 3_000
export const DEFAULT_READINESS_INTERVAL_MS = 100
export const DEFAULT_STOP_TIMEOUT_MS = 5_000
